# Generated by Django 4.2.6 on 2023-10-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poultry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_in_weeks", models.PositiveIntegerField()),
                ("no_of_poultries", models.PositiveIntegerField()),
                ("breed", models.CharField(max_length=50)),
                ("date_add", models.DateField(auto_now_add=True)),
                ("description", models.TextField(default=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farms.farm"
                    ),
                ),
            ],
            options={
                "ordering": ["date_add"],
            },
        ),
    ]
